TIMEOUT = 10

NAME = 'name'
POSITION = 'position'
CONTACT = 'contact'
SUMMARY = 'summary'
EXPERIENCE = 'experience'
EDUCATION = 'education'
VOLUNTEERING = 'volunteering'
SKILLS = 'skills'
PROJECTS = 'projects'
PUBLICATIONS = 'publications'
HONORS = 'honors'
LANGUAGES = 'languages'

ADDRESS = 'address'
MOBILE = 'mobile'
EMAIL = 'email'
HOMEPAGE = 'homepage'
GITHUB = 'github'
LINKEDIN = 'linkedin'
GITLAB = 'gitlab'
STACKOVERFLOW = 'stackoverflow'
TWITTER = 'twitter'
SKYPE = 'skype'
REDDIT = 'reddit'
MEDIUM = 'medium'
GOOGLE_SCHOLAR = 'googlescholar'
