PACKAGE_NAME = 'linkedrw'
TIMEOUT = 10
LATEX_INDENT = '  '
HTML_INDENT = '    '
CREDENTIALS_FILE = f'~/.{PACKAGE_NAME}/credentials.json'

NAME = 'name'
POSITION = 'position'
CONTACT = 'contact'
SUMMARY = 'about'
EXPERIENCE = 'experience'
EDUCATION = 'education'
VOLUNTEERING = 'volunteering'
SKILLS = 'skills'
PROJECTS = 'projects'
PUBLICATIONS = 'publications'
HONORS = 'honors'
LANGUAGES = 'languages'

ADDRESS = 'address'
MOBILE = 'mobile'
EMAIL = 'email'
HOMEPAGE = 'homepage'
GITHUB = 'github'
LINKEDIN = 'linkedin'
GITLAB = 'gitlab'
STACKOVERFLOW = 'stack-overflow'
TWITTER = 'twitter'
SKYPE = 'skype'
REDDIT = 'reddit'
MEDIUM = 'medium'
GOOGLE_SCHOLAR = 'googlescholar'

DATES = 'dates'
LOCATION = 'location'
DESCRIPTION = 'description'
DEGREE = 'degree'
TITLE = 'title'
ENTRIES = 'entries'
DATE = 'date'
LINK = 'link'
PUBLISHER = 'publisher'
ISSUER = 'issuer'

RESUME_TEMPLATE = 'resume_template.tex'
PERSONAL_INFO = [NAME, POSITION, ADDRESS, MOBILE, EMAIL, HOMEPAGE, GITHUB, LINKEDIN, GITLAB, STACKOVERFLOW, TWITTER,
                 SKYPE, REDDIT, MEDIUM, GOOGLE_SCHOLAR]
RESUME_CONTENT = [EDUCATION, EXPERIENCE, PUBLICATIONS, HONORS, PROJECTS, VOLUNTEERING, SKILLS]
RESUME_SECTIONS = [EDUCATION, EXPERIENCE, HONORS, PROJECTS, VOLUNTEERING]
SECTION_ITEMS = {
    EDUCATION: [DEGREE, NAME, LOCATION, DATES, DESCRIPTION],
    EXPERIENCE: [TITLE, NAME, LOCATION, DATES, DESCRIPTION],
    HONORS: [TITLE, ISSUER, LOCATION, DATE],
    PROJECTS: ['', NAME, '', DATES, DESCRIPTION],
    VOLUNTEERING: [TITLE, NAME, LOCATION, DATES, DESCRIPTION]
}

PORTFOLIO_TEMPLATE = 'index_template.html'
PORTFOLIO_SECTIONS = [SUMMARY, EXPERIENCE, EDUCATION, PROJECTS, SKILLS, CONTACT]
CONTACTS = [GITHUB, LINKEDIN, GITLAB, STACKOVERFLOW, TWITTER, REDDIT, MEDIUM]
